name: Publish to Image Repository and and pushing to docker container
on:
  pull_request:

  # push:
  #   branches:
  #     - main

jobs:
  build_and_deploy_cloud_run:
    name: Build Docker image and publish
    runs-on: ubuntu-latest
    steps:

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_CREDS }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true
      - name: Configure Docker credentials
        run: |
          gcloud auth configure-docker europe-docker.pkg.dev  # configure Docker credentials
      - name: Build and push
        run: |
          cd ${{env.GITHUB_WORKSPACE}}
          docker build -t europe-docker.pkg.dev/cognite-inso-sandbox/inso/flasshoff-streamlit-demo:latest .
          docker push europe-docker.pkg.dev/cognite-inso-sandbox/inso/flasshoff-streamlit-demo:latest
