name: Publish to Image Repository and and pushing to docker container
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_cloud_run:
    name: Build Docker image and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_CREDS }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true
      - name: Configure Docker credentials
        run: |
          gcloud auth configure-docker europe-docker.pkg.dev  # configure Docker credentials
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: europe-docker.pkg.dev/cognite-inso-sandbox/inso/flasshoff-streamlit-demo:latest
